object Libs {

    const val coreKtx = "androidx.core:core-ktx:${Versions.coreKtx}"
    const val googleAndroidMaterial = "com.google.android.material:material:${Versions.googleAndroidMaterial}"
    const val constraintLayout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayout}"
    const val hiltAndroid = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val hiltCompiler = "com.google.dagger:hilt-android-compiler:${Versions.hilt}"
    const val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    const val loggingInterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp}"
    const val gson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    const val moshi = "com.squareup.moshi:moshi:${Versions.moshi}"
    const val moshiKotlin = "com.squareup.moshi:moshi-kotlin:${Versions.moshi}"
    const val moshiKotlinCodegen = "com.squareup.moshi:moshi-kotlin-codegen:${Versions.moshi}"
    const val moshiConverterRetrofit = "com.squareup.retrofit2:converter-moshi:${Versions.moshiConverterRetrofit}"
    const val kotlinCoroutineAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${Versions.kotlinCoroutineAndroid}"
    const val kotlinCoroutineCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Versions.kotlinCoroutineAndroid}"
    const val lifecycleExtensions = "android.arch.lifecycle:extensions:${Versions.lifecycleExtensions}"
    const val lifecycleViewModelKtx = "androidx.lifecycle:lifecycle-viewmodel-ktx:${Versions.lifecycleViewModelKtx}"
    const val lifecycleRuntimeKtx = "androidx.lifecycle:lifecycle-runtime-ktx:${Versions.lifecycleRuntimeKtx}"
    const val activityKtx = "androidx.activity:activity-ktx:${Versions.activityKtx}"
    const val glide = "com.github.bumptech.glide:glide:${Versions.glide}"
    const val timber = "com.jakewharton.timber:timber:${Versions.timber}"
    const val roomRuntime ="androidx.room:room-runtime:${Versions.room_version}"
    const val roomKapt = "androidx.room:room-compiler:${Versions.room_version}"

}